# Generated by Django 3.1.2 on 2021-06-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_auto_20210616_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('1', 'Doing'), ('2', 'Done')], max_length=8),
        ),
    ]
